from __future__ import annotations

import csv
import json
from pathlib import Path


def write_evidence(ledger: dict, out: Path) -> None:
    out.mkdir(parents=True, exist_ok=True)
    _write_findings_csv(out / "findings.csv", ledger["findings"])
    _write_poam(out / "poam.csv", ledger["findings"])
    _write_overdue(out / "overdue.csv", ledger["findings"])
    (out / "brief.md").write_text(_brief_md(ledger), encoding="utf-8")
    (out / "drift.md").write_text(_drift_md(ledger), encoding="utf-8")
    (out / "exceptions.md").write_text(_exceptions_md(ledger), encoding="utf-8")
    (out / "handoff.md").write_text(_handoff_md(ledger), encoding="utf-8")
    (out / "attestation.json").write_text(
        json.dumps(
            {
                "tool": ledger["tool"],
                "version": ledger["version"],
                "as_of": ledger["generated_for"],
                "site": ledger["site"].get("name"),
                "statement": (
                    "Produced offline from scanner exports and backup records. "
                    "This register did not scan a host and did not change one."
                ),
                "sources": ledger["sources"],
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    host_dir = out / "by-host"
    host_dir.mkdir(exist_ok=True)
    by_host: dict[str, list] = {}
    for finding in ledger["findings"]:
        by_host.setdefault(finding["host"], []).append(finding)
    for host, findings in by_host.items():
        lines = [f"# {host}", ""]
        for finding in findings:
            if finding["clock"] == "closed":
                continue
            lines.append(f"## {finding['control']} — CAT {finding['cat']} — {finding['clock']}")
            lines.append("")
            lines.append(finding["title"])
            lines.append("")
            lines.append(f"Due: {finding['due'] or 'n/a'}. Class: {finding['remediation']['class']}.")
            lines.append("")
            lines.append(finding["remediation"]["why"])
            lines.append("")
        (host_dir / f"{host.split('.')[0]}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_remediation_plan(ledger: dict, out: Path) -> None:
    out.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by the findings register. Read it before you run anything.",
        "# Tags under `automate` are the only ones the sample playbook should get on an unattended run.",
        "windows:",
    ]
    for window in ledger["windows"]:
        auto = [item["control"] for item in window["items"] if item["class"] == "automate"]
        held = [f"{item['control']} ({item['class']})" for item in window["items"] if item["class"] != "automate"]
        lines.append(f"  - host: {window['host']}")
        lines.append(f"    note: {json.dumps(window['note'])}")
        lines.append("    automate_controls:")
        if auto:
            for control in auto:
                lines.append(f"      - {control}")
        else:
            lines.append("      []")
        lines.append("    hold:")
        if held:
            for control in held:
                lines.append(f"      - {json.dumps(control)}")
        else:
            lines.append("      []")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_findings_csv(path: Path, findings: list[dict]) -> None:
    fields = [
        "host",
        "control",
        "vuln_num",
        "rule_id",
        "cve",
        "title",
        "cat",
        "clock",
        "first_seen",
        "last_seen",
        "due",
        "days_overdue",
        "remediation_class",
        "cci",
        "flags",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for finding in findings:
            writer.writerow(
                {
                    "host": finding["host"],
                    "control": finding["control"],
                    "vuln_num": finding.get("vuln_num") or "",
                    "rule_id": finding.get("rule_id") or "",
                    "cve": finding.get("cve") or "",
                    "title": finding["title"],
                    "cat": finding["cat"],
                    "clock": finding["clock"],
                    "first_seen": finding["first_seen"],
                    "last_seen": finding["last_seen"],
                    "due": finding["due"] or "",
                    "days_overdue": finding["days_overdue"],
                    "remediation_class": finding["remediation"]["class"],
                    "cci": " ".join(finding["cci"]),
                    "flags": " ".join(finding["flags"]),
                }
            )


def _write_poam(path: Path, findings: list[dict]) -> None:
    fields = [
        "POA&M ID",
        "Weakness",
        "Asset",
        "Control",
        "CAT",
        "Source",
        "Original detection",
        "Scheduled completion",
        "Status",
        "Milestone",
        "CCI",
        "NIST",
        "Comments",
    ]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        number = 1
        for finding in findings:
            if finding["clock"] == "closed":
                continue
            if finding["clock"] == "excepted":
                status = "Risk accepted"
                milestone = "Revisit on the exception end date."
            elif finding["clock"] == "overdue":
                status = "Ongoing, past due"
                milestone = finding["remediation"]["summary"]
            else:
                status = "Ongoing"
                milestone = finding["remediation"]["summary"]
            writer.writerow(
                {
                    "POA&M ID": f"POAM-{number:03d}",
                    "Weakness": finding["title"],
                    "Asset": finding["host"],
                    "Control": finding["control"],
                    "CAT": finding["cat"],
                    "Source": ",".join(finding["history"][-1]["sources"]),
                    "Original detection": finding["first_seen"],
                    "Scheduled completion": finding["due"] or "",
                    "Status": status,
                    "Milestone": milestone,
                    "CCI": " ".join(finding["cci"]),
                    "NIST": " ".join(finding["nist"]),
                    "Comments": finding["comments"] or finding["detail"],
                }
            )
            number += 1


def _write_overdue(path: Path, findings: list[dict]) -> None:
    _write_findings_csv(path, [item for item in findings if item["clock"] == "overdue"])


def _brief_md(ledger: dict) -> str:
    lines = [f"# ISSO brief — {ledger['site'].get('name', 'site')}", ""]
    for paragraph in ledger["brief"]["paragraphs"]:
        lines.append(paragraph)
        lines.append("")
    return "\n".join(lines)


def _drift_md(ledger: dict) -> str:
    lines = ["# Drift", ""]
    for name in ("regressed", "new", "closed", "persistent", "opened_since_baseline"):
        rows = ledger["drift"][name]
        lines.append(f"## {name.replace('_', ' ')} ({len(rows)})")
        lines.append("")
        if not rows:
            lines.append("None.")
            lines.append("")
            continue
        for row in rows:
            lines.append(f"- {row['control']} on {row['host']} — {row['title']}")
        lines.append("")
    return "\n".join(lines)


def _exceptions_md(ledger: dict) -> str:
    lines = ["# Exceptions", ""]
    for item in ledger["exceptions"]:
        lines.append(f"## {item['id']} — {item['display_status']} — {item['control']}")
        lines.append("")
        lines.append(item.get("rationale", ""))
        lines.append("")
        lines.append(f"Compensating control: {item.get('compensating', '')}")
        lines.append("")
        lines.append(f"Approver: {item.get('approver_name', '')} ({item.get('approver', '')}). Expires {item.get('expires', '')}.")
        lines.append("")
    return "\n".join(lines)


def _handoff_md(ledger: dict) -> str:
    ready = "ready" if ledger["handoff"]["ready"] else "not ready"
    lines = [f"# Steady-state handoff — {ready}", ""]
    for gate in ledger["handoff"]["gates"]:
        lines.append(f"- **{gate['status'].upper()}** {gate['title']}. {gate['detail']}")
    lines.append("")
    return "\n".join(lines)
